Wrap add_payment_method block in a `to_prepare` block
Fixes the following error when running `bundle exec rspec`:

```
NameError: uninitialized constant SolidusPaypalCommercePlatform::PaymentMethod
```

Allows SolidusPaypalCommercePlatform::PaymentMethod to autoload on boot
in Rails 7.

We need to wrap the initializer in a `to_prepare` block in order for the
initializer to rerun after each reload.

For more information, please see
https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#use-case-1-during-boot-load-reloadable-code.